version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: myschedule360-db
    environment:
      POSTGRES_DB: myschedule360
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: src/myschedule360.API/Dockerfile
    container_name: myschedule360-api
    ports:
      - "5000:8080"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=myschedule360;Username=postgres;Password=postgres

volumes:
  postgres_data: