using Microsoft.EntityFrameworkCore.Migrations;

namespace myschedule360.Infrastructure.Migrations
{
    public partial class ApplySnakeCaseNamingConvention : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // This migration will be automatically generated by EF Core
            // when you run the Add-Migration command
            
            // The actual SQL will be generated based on the differences between
            // the current model and the previous model
            
            // If you need to manually apply SQL, you can use:
            // migrationBuilder.Sql(@"SQL SCRIPT HERE");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Revert changes if needed
        }
    }
}